### ISSUE TITLE
Hvilke alternativer eksisterer allerede?

### ISSUE THREAD

**Issue by Kaliahh** [P7-Team/P7-Report#3]
Hvilken arkitektur bruger de? 

Hvilke klasser af problemer understøtter de? Hvad specialiserer de sig i? 

Hvilke begrænsninger har de?

**Comment by Kaliahh** [comment]
Forslag:

Golem (Done)

Vast.AI (Done)

CLAAUDIA (Done)

Supercomputere generelt (Done)

Entropia: [Entropia](https://cseweb.ucsd.edu/~calder/papers/JPDC-Entropia.pdf) (Done)

~~Universal Devices, som blev til: Univa UD, som så hvidst er blevet Altair [UnivaUD](https://www.altair.com/hpc-cloud-applications/)~~ (Alexander) <- Der var ikke noget information at finde, med mindre man ville i kontakt med deres sales department.

Distribueret netværk generelt (Done)

**Comment by dkalaxdk** [comment]
# General Terms


- Grid computing: Localized syncronous computing, usually done within an orginization where the computers are ususally active at the same time. Here the devices on the network are also usually trusted, therefore the results may not need to be redundantly distributed to other devices.

- Volunteer computing/distributed computing, here the devices are not neccesarliy trusted, as the general public can join into the projects. Their connection patterns aren't known from the host either.

- Connection patterns: The pattern defining when a provider is online, and the amount of GPU/CPU work the provider is capable of providing at the given time.



# Golem
Golem is a distributed network which allows users to define assignments which can be completed by other devices, in return for the "Golem" coin.


Golem is:

 - Accessible
 - Reliable
 - Open access
 - Censorship resistant protocol.


## Used for:
 - Machine learning
 - Data analytics
 - Video transcoding
 - Cad simulators
 - Chemistry simulations
 - Image and video rendering



## Architecture

Peer to Peer communication, however limited by NAT. (In progress of developing a relay)
Hybrid P2P also in progress.
[Architecture](https://github.com/golemfactory/yagna#list-of-implemented-and-planned-functionality)

## Limitations

It is limited in the fact that it costs money, this can however also be a motivating factor.
Currently no apparent verification of data is made.

Planning on implementing gWASM as an alternative to redundant checking of results. <br>
The redundant checking have been down prioritized due to the general computational and network overhead of redundancy. The reason it does not work in Golem is that it costs more to fact check the results on multiple devices, as they get payed for the computation time.

To increase the efficiency of cross checking the computations are firstly done on two devices, if those disagree on the result, it is then distributed to another device, to see which of the results are correct.
This can ONLY be done on deterministic results.

One of the advantages of doing it like this, is that devices with high error rates can be rated as less reliable, and therefor do not get as many tasks, therefore resulting in an overall more efficient network, where incorrect devices eventually gets phased out of the network.

# Vast.AI

Decentralized GPU rental.

Is a market place to connect different private and company vendors into one marketplace, thereby allowing a general price overview of prices at different locations.


Works by the vendors installs the Vast program, which then allows the GPU to be put to work through the Vast system.
Usually an SSH is given as access to the GPU. Or a Jupyter gui/notebook.

GPUS

## Architecture

Not apparent.

But seems to be connections relayed through the website. Where their program runs a connection which can be remoted into through vast.io.



## What problems do they solve?

Anything done on a GPU, which can be achieved through SSH.
Primarily the use cases seems to be AI training.

### Speciality

AI

## Limitations

Only GPU rental, and they state that "it is difficult to make it secure (From hosts), further/better security might be implemented in the future."


# BOINC

BOINC is a research based distributed computation network made my Berkley California

## Architecture and general technical ideas

Architecture seems to be P2P with a central server. The central server stores the currently available jobs, and connects the devices to the requested job. 


As BOINC points out, some results may not be entirely identical on different devices, as some devices integers/floats etc may be implemented differently on different systems. Therefore BOINC allows for something called "homogeneous redundancy", which can be enabled my the creator of a BOINC program. <br>
Homogeneous redundancy will send each workload to similar machines (Same CPU vendor, same OS etc)

BOINC uses "Exponential backoff" which will distribute the data connections to a given device in case of an error. ". Thus, if a BOINC server comes up after an extended outage, its connection rate will be the long term average." [src](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1382809)


Any job includes a timeout value, which can be used to set an upper bound to the calculation time. 

When multiple devices need to use shared data (Such as a DB or a file), a semaphore is used to lock access to the data.


BOINC can both be used for volunteer computing and for in-house computing.[Usages](https://boinc.berkeley.edu/trac/wiki/BoincOverview) <br>

 - Volunteer computing is the "classic" BOINC usage where the project is made availabe to all users of boinc, and where the general public can join into the project.

 - In House: In this case case the worker nodes are cluster nodes or other organizational computers, and they are attached to the organization's server. And can thereby be used for Grid-Computing


## What problems do they solve?

The focus of BOINC is research and to allow users to "rent" out their system to research in return for BOINC credits, which works as a high score system. <br>

BOINC both have problems which runs through CPUs and GPUs. <br>

As it it focused on resarch the interface to the system have been developed to not require a degree in computer science, but one should theoretically be able to get a project up and running after a few hours of reading and working on the project.

### Speciality

Research.
As a result it allows users to support the topics they are interested in. Through the "Science United" page, a user can join a general topic of projects, and then help with multiple different projects within the same research topic.

## Limitations

As BOINC runs on a linux VM, and allows for gridcomputing as well, the limitations of the system is generally rather limited. <br>
However, the general focus of the BOINC network is research, so setting up a public project which is not research related, using BOINC, may be more difficult to gather providers for.

**Comment by naitoarekkus** [comment]
Jeg prøver med CLAAUDIA

**Comment by AxialDark** [comment]
## Supercomputers in general

**Links**:
- Supercomputer architectures
    - [CLEX](https://arxiv.org/abs/1607.00298)
    - [Blue Gene/L torus](https://ieeexplore.ieee.org/abstract/document/5388784)
    - [DAS](https://dl.acm.org/doi/abs/10.1145/506106.506115)
    - [Nectar](https://ieeexplore.ieee.org/abstract/document/532117)
- [Myrinet](https://ieeexplore.ieee.org/abstract/document/342015)
---
Exploration of **CLEX**:
### Architecture
- Potentially other architectures to examine: State-of-the-art architectures like Cray XMT or IBM Blue Gene
- Basically they collect the nodes of the supercomputer (processers) into cliques of nodes, such that there is a minimum distance between nodes in the cliques.
    - These cliques are then arrenged in levels such that lower level cliques can be part of a higher level one.
    - This allows the communication to and from cliques to go through individual nodes with higher capacity communication paths and ensures low delay in the communication between nodes within a clique

### Limits
- This means that the distance between nodes should be very small, which also means that it would probably not scale to internet spanning distributed networks.

### Class of problems
- Not specified or mentioned
---
Exploration of **Blue Gene/L torus**:
### Architecture
- Uses a Torus network architecture between computation nodes
- This arrange the nodes in a 3D cubic grid and connected to its 6 nearest neighbors through high speed dedicated links
    - This allows "routing" to be based on a 3-dimentional coordinate grid, which can give "hints" as to which directions the messages can be passed to reach its destination. (Routing free)
- Messages communicated conforms to the *Message Passing Interface Standard (MPI)*

### Limits
- The message passing can deadlock, but bubble virtual channels can be used to resolve these.

### Class of problems
- Not specified or mentioned
---
Exploration of **DAS**:
### Architecture
- Consists of 4 physical distributed cluster of homogenous computers (same processors, local network, and operating system)
- Each cluster is internally connected using high-speed ethernet and the local clusters are then connected by an *Asynchronous Transfer Mode (ATM)* based *virtual private network (VPN)*.
- Myrinet was selected as local network, because it was by far the fastest of the networks considered. Myrinet is a switch-based network using wormhole routing

### Limits
- Access is limited to faculty and students of the computer science groups in the ASCI research groups and a few of their sponsors.

### Class of problems
- Research in the areas of:
    - Parallel language
    - Communication software
    - Schedulers
    - Parallel applications
    - Distributed applications
---
Exploration of **Nectar**:
### Architecture
- The network consists of crossbar switches (HUBs) and each node which is connected to the network is connected using a 100Mbits\sec fiber-optic links.
- The nodes (hosts) connect to the network through the *Communication Acceleration Boards (CAPs)* (hardware component), which is an interface handling the communication to and from the network to the host.
    - The CAB can communicate using both UDP and TCP.

### Limits
- The peak reached at the time was 26 hosts connected to the network.

### Class of problems
- It was used in tandem with COSMOS: A logic simulation application
- It was used in tandow with NOODLES: A geometric modelling application
- Simulation

**Comment by AxialDark** [comment]
## Entropia
Link to paper [here](https://cseweb.ucsd.edu/~calder/papers/JPDC-Entropia.pdf)

### Architecture
- The applications which are to be run on the system are "wrapped" in their virtual machine technology
- Uses an layered architecture with 3 layers
    - Job Management Layer: The top layer that the end user usually interacts with, it provides management facilities for handling large numbers of computations and files. This also breaks large tasks into a bunch of subtasks. 
    - Resource Scheduling Layer: Is the middle layer, it provides resource matching, scheduling, and fault tolerance.  
    - Physical Node Layer: Is the bottom layer, it provides communication, security, and resource management.

### Limits
- Runs only on win32 systems

### Class of problems
- [Molecular docking](https://www.sciencedirect.com/science/article/pii/B9780128015056000107#s0100)
- [Sequence analysis](https://en.wikipedia.org/wiki/Sequence_analysis#:~:text=In%20bioinformatics%2C%20sequence%20analysis%20is,against%20biological%20databases%2C%20and%20others.)
- Chemical structure modeling
- Risk management
- Data mining
- Financial modeling

**Comment by AxialDark** [comment]
## Distributed Networks in generel

**Links**:
- [Distributed SOA](https://ieeexplore.ieee.org/abstract/document/5076939)

Exploration of **Distributed SOA:**

SOA = Service Oriented Archtecture

### Architecture
- Generally, the architecture is that each service is standalone and provides a functionality. Each services then have an API, which describes how to communicate with the service. The idea is that the services can call each other if they need the functionality provided by another service, this avoids having to develop the same functionality in multiple services which then have to be updated independant of each other. This allows services to be combined to solve larger/complex problems.
- This architecture can also be layered. In the paper linked they describe 4 distinct layers that would work within an enterprise. From top to bottom.
    1. Presentation layer: Handles the man to machine interactions, e.g. takes requests from users and calls the related service on the Business process layer
    2. Business process layer: Deals with the flow needed to fulfill the requests of the users. Calls the necessary services on the Business logic layer to complete the request.
    3. Bussiness logic layer: Handles the complex business logic to fulfill parts of a request.
    4. Data layer: Handles the data stored in databases.
- This architecture also depends on a discovery service, in order for the services to know which service is where, if they need to communication with them.

### Limits
- Basic architecture, that needs to be adapted to work in the context of the system.

### Class of problems
- Depends on the system
